project 'Get together.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Get together' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Get together
  
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SVProgressHUD'
  pod 'GoogleSignIn'
    pod 'FacebookCore'
  pod 'FacebookLogin'


end
